### ISSUE TITLE
GitHub won't let me fork an empty repo.

### ISSUE THREAD

**Issue by tangmi** [StudentRND/s5#1] opened 2014-02-07 05:06 UTC

**Comment by tylermenezes** [comment] 2014-04-30 02:58
@tangmi can you confirm this issue was resolved in 0272eb8136?

**Comment by tangmi** [comment] 2014-04-30 05:10
I have commit (null) in production and the problem persists. Is it possible to create a hotfix for version 0.0.0?

**Comment by tjhorner** [comment] 2015-02-23 17:40
Forked repo. Can't reproduce. Should be fixed in 0272eb8.

**Closed as completed by tjhorner** 2015-02-23 17:40 UTC
